### ISSUE TITLE
Missing reflection

### ISSUE THREAD

**Issue by remicollet** [SeasX/PHP-Druid#1]
From `php --re druid`, lot of methods don't have any arg info.

**Comment by remicollet** [comment]
will open a PR

**Comment by Neeke** [comment]
fixed with 0.9.0

**Comment by remicollet** [comment]
Thanks,

I notice you update 0.8.0 (7a3bc5466c5efe8bd6b43fdad2f18ee20553acae) and 0.9.0 (b2a7feeeeb73c5eb374ce9df79d0b0a3db9cb2a2) but I don't see any tagged version nor pecl version ?

**Comment by Neeke** [comment]
@remicollet  same version is private or dev, do not beta / release.

**Comment by remicollet** [comment]
Sorry, too late, I have already release 0.9.0 in my repo.

https://github.com/Neeke/PHP-Druid/releases/tag/PHP-Druid-v0.9.0 is published as "Latest release"

If you create some "dev"  tag, please don't create release, or, better, create  "pre-release" (if this case I usually build them for test, and push in my testing repo). You can also use dev, alpha, beta, RC as part of the release name.
